name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  version: 1.0.0
  name: pyworld
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.name}}:${{ env.version }}
    - name: Run the docker image 
      run: docker run -d -p 8888:8080 ${{ env.name}}:${{ env.version }}
    - name: Check for output 
      run: |
        curl --silent http://localhost:8888|grep "Hello World"
